# --- !Ups
CREATE TABLE INTEGRATION (
    INTEGRATION_ID SERIAL PRIMARY KEY,
    INTEGRATION_NAME VARCHAR NOT NULL UNIQUE,
    DS_ONE_ID INT NOT NULL,
    DS_TWO_ID INT NOT NULL,
    BLOCKING_ALG VARCHAR,
    COMPARISON_ALG VARCHAR,
    SAME_DS_COMP BOOLEAN,
    THRESHOLD FLOAT,
    READY BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (DS_ONE_ID) REFERENCES DATASET(DATASET_ID),
    FOREIGN KEY (DS_TWO_ID) REFERENCES DATASET(DATASET_ID)
);

CREATE TABLE SIMILARITY (
    SIMILARITY_ID SERIAL PRIMARY KEY,
    INTEGRATION_ID INT NOT NULL,
    ROW_DS_ONE_ID INT NOT NULL,
    ROW_DS_TWO_ID INT NOT NULL,
    SIMILARITY FLOAT,
    FOREIGN KEY (INTEGRATION_ID) REFERENCES INTEGRATION(INTEGRATION_ID)
    ON DELETE CASCADE
);


# --- !Downs
DROP TABLE INTEGRATION;
DROP TABLE SIMILARITY;